void lignelettre0(char[1],int,int,int,WORD, booleen);
void lignelettre1(char[1],int,int,int,WORD, booleen);
void colonnelettre0(char[1],int,int,int,WORD, booleen);
void colonnelettre1(char[1],int,int,int, WORD, booleen);
void diagolettre(char[1],int,int,int,WORD, booleen);
void diagolettre1(char [1],int ,int , int ,WORD , booleen );

void A(int , int ,WORD ,booleen);
void B(int , int ,WORD ,booleen);
void C(int , int ,WORD ,booleen);
void D(int , int ,WORD ,booleen);
void E(int , int ,WORD ,booleen);
void F(int , int ,WORD ,booleen);
void G(int , int ,WORD ,booleen);
void H(int , int ,WORD ,booleen);
void I(int , int ,WORD ,booleen);
void J(int , int ,WORD ,booleen);
void K(int , int ,WORD ,booleen);
void L(int , int ,WORD ,booleen);
void M(int , int ,WORD ,booleen);
void N(int , int ,WORD ,booleen);
void O(int , int ,WORD ,booleen);
void P(int , int ,WORD ,booleen);
void Q(int , int ,WORD ,booleen);
void R(int , int ,WORD ,booleen);
void S(int , int ,WORD ,booleen);
void T(int , int ,WORD ,booleen);
void U(int , int ,WORD ,booleen);
void V(int , int ,WORD ,booleen);
void W(int , int ,WORD ,booleen);
void X(int , int ,WORD ,booleen);
void Y(int , int ,WORD ,booleen);
void Z(int , int ,WORD ,booleen);

void UN(int , int , WORD ,booleen);
void DEUX(int , int ,WORD, booleen);
void TROIS(int, int ,WORD,booleen);
void QUATRE(int,int,WORD,booleen);
void CINQ(int, int ,WORD,booleen);
void SIX(int, int ,WORD,booleen);
void SEPT(int, int ,WORD,booleen);
void HUIT(int, int ,WORD,booleen);
void NEUF(int, int ,WORD,booleen);
void ZERO(int, int ,WORD,booleen);
void EXCL(int ,int  ,WORD ,booleen );


void cadre(char [3],int , int , int , int , WORD );
void affiche_nom_joli (char [50], int, int , booleen );
void Dessintrain (int, int);
void Dessincompagnie ( int, int, WORD );
void Dessinpanneau (void);
void innPropriete (void );
void Animejoueur (void);
void Animetrain (void);
void Dessinpion (int,int);
void innGare(void);
void innComp(void);
void innVisiteprison(void);
void dessinBarreaux(int,int);
void Traversejoueurprison2(void);
void Dessinprison(void);
void innPrison(void);
void affiche_prison(void);
void Animegeantjoueur1(void);
void Traversejoueurprison1(void);
void Dessinjoueurinprison(void);
void outjoueurprison(void);
void psgeDep(void);
void initpaysg(void);
void initpaysp(void);
void innParc(void);
void CaisseC(void);
void CarteCh(void);
void innimpotRev(void);
void inntaxeLux(void);
void gagne(void);
void perdu(void);




void grille2(char[1],int,int,int,WORD);
/*void prison1(int , int , WORD );*/
void affiche_nom(char *, int, int , WORD ,booleen);
void animIntro(void);
void prison2(void);